---
- name: Configure Hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root

- name: Execute Hostname
  action: shell sudo hostname -F /etc/hostname

- name: Change hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root

- name: pycurl
  apt: name=python-pycurl state=present

- name: Add Java repo
  apt_repository: repo='ppa:webupd8team/java' state=present update_cache=yes

- name: Autoaccept license for Java
  action: shell echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Update APT package cache
  action: apt update_cache=yes

- name: Installing java
  apt: name=oracle-java8-installer state=present update_cache=yes

- name: Kafka Download
  get_url: url=http://www-eu.apache.org/dist/kafka/0.9.0.0/kafka_2.10-0.9.0.0.tgz dest=/root/

- name: Unarchive Kafka
  unarchive: src=/root/kafka_2.10-0.9.0.0.tgz dest=/root/ copy=no

- name: Creates Zookeeper directroy
  file: path=/root/zookeeper state=directory

- name : Zookeeper file myid
  template:
    src: myid.j2
    dest: /root/zookeeper/myid
    owner: root
    group: root

- name: Configure Zookeeper
  template:
    src: zookeeper.properties.j2
    dest: /root/kafka_2.10-0.9.0.0/config/zookeeper.properties

- name: Configure Kafka
  template:
    src: server.properties.j2
    dest: /root/kafka_2.10-0.9.0.0/config/server.properties

- name : Kafka Init
  template:
    src: kafka.conf.j2
    dest: /etc/init/kafka.conf
    owner: root
    group: root
